### ISSUE TITLE
Add some mark that parameters as invalid/unavailable

### ISSUE THREAD

**Issue by elupus** [yozik04/nibe#13]
When a parameter is not available, the pump sets the parameter to 0xFFFF. Would be nice to have the value field become None in that case, or some other mark.

**Comment by yozik04** [comment]
Interesting what value it sends for undefined uint8 and uint32.

**Comment by yozik04** [comment]
1. For int 32 `b"\xff\xff\xff\xff" = -1`
2. For int 16 `b"\xff\xff" = -1`

**Comment by yozik04** [comment]
Let's move discussion to PR.
