### ISSUE TITLE
Add support for external energy meter BE6

### ISSUE THREAD

**Issue by Freiheiter** [yozik04/nibe#138]
Got the external pulse energy meter (based on the S0 interface) to work with my Nice S1255-6 PC over modbusTCP and thought I'd share how.

I'm aware that my setting is against the spec, which claims the register to be 398 for BE6, and with an offset of 30001 we should end up at 30399. But the USB-extract retrieved from the pump gives 396, and the respective 30397 works like a charm. So I suspect the spec is in error here. Please consider for a merge.

Here's what I added to s1155_s1255.json:

"30397": {
"title": "Pulse energy meter (BE6/BF2)",
"factor": 100,
"size": "u32",
"unit": "kWh",
"name": "pulse-energy-meter-be6-bf2-30397"
},

**Comment by Andy-Voigt** [comment]
Same for the s320

**Comment by yozik04** [comment]
@Andy-Voigt can you please temporarily change heat pump language to English and then do the export.

**Comment by Andy-Voigt** [comment]
[modbus_addresses_all_20240704-06920621343032-1.csv](https://github.com/user-attachments/files/16095569/modbus_addresses_all_20240704-06920621343032-1.csv)

Here is the csv in English.

**Comment by yozik04** [comment]
I will. Thank you.

**Comment by Andy-Voigt** [comment]
Is it realy a read only register?

**Comment by Freiheiter** [comment]
By the specs, it is read-only.
The value is calculated from pulses received from an external contact, typically connected to an electricity meter, using the protocol S0 as in EN 62053-31
It might be helpful to be able to overwrite that values (for example, if it diverges from the meter's physical display for whatever reason), but by the specs, this can't be done.
