### ISSUE TITLE
erroneous modbus values eb100-beX - NibeGW ESPHOME - F1255

### ISSUE THREAD

**Issue by MichaelPihlblad** [yozik04/nibe#159]
Getting these erroneous values in homeassistant:

```
INFO (MainThread) [nibe.nibe.connection.nibegw] Coil eb100-be3-current-40079, value: 13107.2
INFO (MainThread) [nibe.nibe.connection.nibegw] Coil eb100-be2-current-40081, value: 65536.0
INFO (MainThread) [nibe.nibe.connection.nibegw] Coil eb100-be1-current-40083, value: 32768.0
```

Checked the csv and json files for F1255 and they are correct.

It used to work with the same heat pump while using NibePI. So most likely not the heatpump raw values that are incorrect.

**Comment by elupus** [comment]
Change your wordswap setting

**Comment by MichaelPihlblad** [comment]
Thanks, I was thinking it could possibly be byte order issue to look into in this lib.

But there is an option in the heat pump to swap the byte order, available over modbus even, and that solves the issue.
