### ISSUE TITLE
Fan speed current shows wrong %

### ISSUE THREAD

**Issue by tizianodeg** [yozik04/nibe#164]
Instead of showing the current % of the fan, it shows a number between 0-4.

eg. if Fan Mode 2 is 30% it shows:
![image](https://github.com/yozik04/nibe/assets/65893913/8141fa6e-f4c7-45f3-812b-e096ecd87cbf)

I do not see how we can take the current configured % with extensions.json
This would be the best we can do without bigger changes:
![image](https://github.com/yozik04/nibe/assets/65893913/4433d4c8-220b-440e-a930-4e075bf3d7d3)

see also #111

**Comment by elupus** [comment]
Should be solved now.
