### ISSUE TITLE
Additional undocumented registers for F1255

### ISSUE THREAD

**Issue by Archomeda** [yozik04/nibe#175]
I've moved from nibepi to nibegw via esphome in my HA installation, and I realized afterwards that I added additional undocumented registers in my old setup.

What is the policy for having these undocumented registers added to this library?

The registers I found by using my config backup are as follows:
Register | Factor | Size | Mode | Min | Max | Title | Info
----|----|----|----|----|----|----|----
48044 | 1 | u16 | Read-only? | 0 | 65535 | Holiday - Start date | Days since 2007-01-01
48045 | 1 | u16 | Read-only? | 0 | 65535 | Holiday - End date | Days since 2007-01-01
47052 | 1 | u32 | R/W | 0 | 86400 | Periodic HW time of day | Time of day in seconds when periodic HW is activated

For the periodic HW time register, I've had mixed results when writing to it. I believe it only allows writing whole hours as value.
And sadly I wasn't able to write the holiday dates to my F1255 using nibepi, which would've been useful.

**Comment by elupus** [comment]
We add them to the extension file an regenerate the data. Feel free to open a pull.
