### ISSUE TITLE
Allow listening to multicast address

### ISSUE THREAD

**Issue by elupus** [yozik04/nibe#20]
It would be nice to configure the gateway device to send to a multicast address.

To make this work properly, the socket needs to be manually constructed and passed to create_datagram_endpoint. This is requires since the standard function will not join multicast addresses, which mean it will not work on setups where switches or wlan access points have igmp snooping enabled.

**Comment by yozik04** [comment]
You want multicast for what? Do you want to configure NibeGW on microcontroller to send multicast packets?

**Comment by elupus** [comment]
Yup, to allow nibepi and native to coexist.
